name: myjava project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5

      - name: Dotnet Publish Command
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o /demo
