name: Deploy to Amazon EKS

on:
  push:
    branches: [ "develop", "ci/setup" ]

env:
  DOCKER_IMAGE: portfolio-nopcommerce-dev    # set this to your application's name
  ECR_REGISTRY: 015568130945.dkr.ecr.ap-southeast-1.amazonaws.com/portfolio-nopcommerce-dev
jobs:
  build:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build \
        -t $DOCKER_IMAGE:${{ github.run_number }} \
        .

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        image: $DOCKER_IMAGE:${{ github.run_number }}

  # deploy_to_eks: --> (not recommend to use in production)
  install_to_eks:
    name: Install to EKS
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - run: |
        docker run \
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
        -e KUBECONFIG_FILE_S3_URL=${{ secrets.KUBECONFIG_FILE_S3_URL }} \
        -e EKS_CHART_NAME=$DOCKER_IMAGE \
        -e EKS_CHART_VERSION=${{ github.run_number }} \
        -e EKS_IMAGE_REPOSITORY=$ECR_REGISTRY \
        -e EKS_CONTAINER_PORT=8080 \
        -e EKS_CONTAINER_HEALTH_CHECK_PATH='\' \
        -e RESOURCE_LIMITS_CPU=2000m \
        -e RESOURCE_LIMITS_MEMORY=6Gi \
        -e RESOURCE_REQUEST_CPU=1000m \
        -e RESOURCE_REQUEST_MEMORY=4Gi \
        -e EKS_NAMESPACE='prj-portfolio-nopcommerce' \
        qitpy/aws-eks-helm-deploy:1.4
